# Makefile.in generated by automake 1.11.6 from Makefile.am.
# modules/tools/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# tools/Makefile.am



am__make_dryrun = \
  { \
    am__dry=no; \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        echo 'am--echo: ; @echo "AM"  OK' | $(MAKE) -f - 2>/dev/null \
          | grep '^AM OK$$' >/dev/null || am__dry=yes;; \
      *) \
        for am__flg in $$MAKEFLAGS; do \
          case $$am__flg in \
            *=*|--*) ;; \
            *n*) am__dry=yes; break;; \
          esac; \
        done;; \
    esac; \
    test $$am__dry = yes; \
  }
pkgdatadir = $(datadir)/engine
pkgincludedir = $(includedir)/engine
pkglibdir = $(libdir)/engine
pkglibexecdir = $(libexecdir)/engine
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
subdir = modules/tools
DIST_COMMON = $(libtools_a_HEADERS) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
LIBRARIES = $(noinst_LIBRARIES)
AR = ar
ARFLAGS = cru
libtools_a_AR = $(AR) $(ARFLAGS)
libtools_a_LIBADD =
am__objects_1 =
am__dirstamp = $(am__leading_dot)dirstamp
am_libtools_a_OBJECTS = $(am__objects_1) src/aux.$(OBJEXT) \
	src/date.$(OBJEXT) src/timeserie.$(OBJEXT) \
	src/multimedia/jpegtools.$(OBJEXT) \
	src/algebra/vector3.$(OBJEXT) src/algebra/matrix3.$(OBJEXT) \
	src/algebra/vector4.$(OBJEXT) src/algebra/matrix4.$(OBJEXT) \
	src/algebra/quaternion.$(OBJEXT) src/tree/tnode.$(OBJEXT) \
	src/tree/atree.$(OBJEXT) src/multimedia/csvtools.$(OBJEXT) \
	src/logger.$(OBJEXT) src/afilter/filter.$(OBJEXT) \
	src/afilter/adapfil.$(OBJEXT) src/algebra/matrixn.$(OBJEXT) \
	src/algebra/vectorn.$(OBJEXT) \
	src/algebra/transmatrix.$(OBJEXT) \
	src/multimedia/imagemap.$(OBJEXT) src/timemark.$(OBJEXT) \
	src/timepoint.$(OBJEXT) src/net/msocket.$(OBJEXT)
libtools_a_OBJECTS = $(am_libtools_a_OBJECTS)
DEFAULT_INCLUDES = -I. -I$(top_builddir)
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(libtools_a_SOURCES)
DIST_SOURCES = $(libtools_a_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(libtools_adir)"
HEADERS = $(libtools_a_HEADERS)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /home/igor/proj/bspace/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AM_CXXFLAGS =  -O3 -funroll-loops -std=c++11
AM_LDFLAGS = 
AUTOCONF = ${SHELL} /home/igor/proj/bspace/missing --run autoconf
AUTOHEADER = ${SHELL} /home/igor/proj/bspace/missing --run autoheader
AUTOMAKE = ${SHELL} /home/igor/proj/bspace/missing --run automake-1.11
AWK = mawk
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EXEEXT = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/igor/proj/bspace/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = engine
PACKAGE_BUGREPORT = palmieri.igor@gmail.com
PACKAGE_NAME = Engine
PACKAGE_STRING = Engine 0.1beta
PACKAGE_TARNAME = engine
PACKAGE_URL = 
PACKAGE_VERSION = 0.1beta
PATH_SEPARATOR = :
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 0.1beta
abs_builddir = /home/igor/proj/bspace/modules/tools
abs_srcdir = /home/igor/proj/bspace/modules/tools
abs_top_builddir = /home/igor/proj/bspace
abs_top_srcdir = /home/igor/proj/bspace
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/igor/proj/bspace/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../../
top_builddir = ../..
top_srcdir = ../..
AUTOMAKE_OPTIONS = subdir-objects

# additional include pathes necessary to compile the C++ library
AM_CPPFLAGS = \
		-Iinclude


#AM_LDFLAGS = -ljpeg -lrt

###############################################################################
# THE LIBRARIES TO BUILD
###############################################################################

# the library names to build (note we are building static libs only)
noinst_LIBRARIES = libtools.a

# where to install the headers on the system
libtools_adir = $(includedir)/tools

# the list of header files that belong to the library (to be installed later)
libtools_a_HEADERS = \
			include/tools.h \
			include/adefs.h \
			include/afilter.h \
			include/algebra.h \
			include/aux.h \
			include/date.h \
			include/graph.h \
			include/logger.h \
			include/multimedia.h \
			include/singleton.h \
			include/timeserie.h \
			include/tree.h \
			include/afilter/adapfil.h \
			include/afilter/filter.h \
			include/algebra/matrix3.h \
			include/algebra/matrix4.h \
			include/algebra/matrixn.h \
			include/algebra/quaternion.h \
			include/algebra/transmatrix.h \
			include/algebra/vector3.h \
			include/algebra/vector4.h \
			include/algebra/vectorn.h \
			include/graph/dedge.h \
			include/graph/dgraph.h \
			include/graph/dnode.h \
			include/multimedia/imagemap.h \
			include/tree/atree.h \
			include/tree/tnode.h \
			include/spool.h \
			include/timemark.h \
			include/timepoint.h \
			include/mnet.h \
			include/net/msocket.h


# the sources to add to the library and to add to the source distribution
libtools_a_SOURCES = \
			$(libtools_a_HEADERS) \
			src/aux.cpp \
			src/date.cpp \
			src/timeserie.cpp \
			src/multimedia/jpegtools.cpp \
			src/algebra/vector3.cpp \
			src/algebra/matrix3.cpp \
			src/algebra/vector4.cpp \
			src/algebra/matrix4.cpp \
			src/algebra/quaternion.cpp \
			src/tree/tnode.cpp \
			src/tree/atree.cpp \
			src/multimedia/csvtools.cpp \
			src/logger.cpp \
			src/afilter/filter.cpp \
			src/afilter/adapfil.cpp \
			src/algebra/matrixn.cpp \
			src/algebra/vectorn.cpp \
			src/algebra/transmatrix.cpp \
			src/multimedia/imagemap.cpp \
			src/timemark.cpp \
			src/timepoint.cpp \
			src/net/msocket.cpp

all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu modules/tools/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu modules/tools/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/aux.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/date.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/timeserie.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/multimedia/$(am__dirstamp):
	@$(MKDIR_P) src/multimedia
	@: > src/multimedia/$(am__dirstamp)
src/multimedia/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/multimedia/$(DEPDIR)
	@: > src/multimedia/$(DEPDIR)/$(am__dirstamp)
src/multimedia/jpegtools.$(OBJEXT): src/multimedia/$(am__dirstamp) \
	src/multimedia/$(DEPDIR)/$(am__dirstamp)
src/algebra/$(am__dirstamp):
	@$(MKDIR_P) src/algebra
	@: > src/algebra/$(am__dirstamp)
src/algebra/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/algebra/$(DEPDIR)
	@: > src/algebra/$(DEPDIR)/$(am__dirstamp)
src/algebra/vector3.$(OBJEXT): src/algebra/$(am__dirstamp) \
	src/algebra/$(DEPDIR)/$(am__dirstamp)
src/algebra/matrix3.$(OBJEXT): src/algebra/$(am__dirstamp) \
	src/algebra/$(DEPDIR)/$(am__dirstamp)
src/algebra/vector4.$(OBJEXT): src/algebra/$(am__dirstamp) \
	src/algebra/$(DEPDIR)/$(am__dirstamp)
src/algebra/matrix4.$(OBJEXT): src/algebra/$(am__dirstamp) \
	src/algebra/$(DEPDIR)/$(am__dirstamp)
src/algebra/quaternion.$(OBJEXT): src/algebra/$(am__dirstamp) \
	src/algebra/$(DEPDIR)/$(am__dirstamp)
src/tree/$(am__dirstamp):
	@$(MKDIR_P) src/tree
	@: > src/tree/$(am__dirstamp)
src/tree/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/tree/$(DEPDIR)
	@: > src/tree/$(DEPDIR)/$(am__dirstamp)
src/tree/tnode.$(OBJEXT): src/tree/$(am__dirstamp) \
	src/tree/$(DEPDIR)/$(am__dirstamp)
src/tree/atree.$(OBJEXT): src/tree/$(am__dirstamp) \
	src/tree/$(DEPDIR)/$(am__dirstamp)
src/multimedia/csvtools.$(OBJEXT): src/multimedia/$(am__dirstamp) \
	src/multimedia/$(DEPDIR)/$(am__dirstamp)
src/logger.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/afilter/$(am__dirstamp):
	@$(MKDIR_P) src/afilter
	@: > src/afilter/$(am__dirstamp)
src/afilter/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/afilter/$(DEPDIR)
	@: > src/afilter/$(DEPDIR)/$(am__dirstamp)
src/afilter/filter.$(OBJEXT): src/afilter/$(am__dirstamp) \
	src/afilter/$(DEPDIR)/$(am__dirstamp)
src/afilter/adapfil.$(OBJEXT): src/afilter/$(am__dirstamp) \
	src/afilter/$(DEPDIR)/$(am__dirstamp)
src/algebra/matrixn.$(OBJEXT): src/algebra/$(am__dirstamp) \
	src/algebra/$(DEPDIR)/$(am__dirstamp)
src/algebra/vectorn.$(OBJEXT): src/algebra/$(am__dirstamp) \
	src/algebra/$(DEPDIR)/$(am__dirstamp)
src/algebra/transmatrix.$(OBJEXT): src/algebra/$(am__dirstamp) \
	src/algebra/$(DEPDIR)/$(am__dirstamp)
src/multimedia/imagemap.$(OBJEXT): src/multimedia/$(am__dirstamp) \
	src/multimedia/$(DEPDIR)/$(am__dirstamp)
src/timemark.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/timepoint.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/net/$(am__dirstamp):
	@$(MKDIR_P) src/net
	@: > src/net/$(am__dirstamp)
src/net/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/net/$(DEPDIR)
	@: > src/net/$(DEPDIR)/$(am__dirstamp)
src/net/msocket.$(OBJEXT): src/net/$(am__dirstamp) \
	src/net/$(DEPDIR)/$(am__dirstamp)
libtools.a: $(libtools_a_OBJECTS) $(libtools_a_DEPENDENCIES) $(EXTRA_libtools_a_DEPENDENCIES) 
	-rm -f libtools.a
	$(libtools_a_AR) libtools.a $(libtools_a_OBJECTS) $(libtools_a_LIBADD)
	$(RANLIB) libtools.a

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/afilter/adapfil.$(OBJEXT)
	-rm -f src/afilter/filter.$(OBJEXT)
	-rm -f src/algebra/matrix3.$(OBJEXT)
	-rm -f src/algebra/matrix4.$(OBJEXT)
	-rm -f src/algebra/matrixn.$(OBJEXT)
	-rm -f src/algebra/quaternion.$(OBJEXT)
	-rm -f src/algebra/transmatrix.$(OBJEXT)
	-rm -f src/algebra/vector3.$(OBJEXT)
	-rm -f src/algebra/vector4.$(OBJEXT)
	-rm -f src/algebra/vectorn.$(OBJEXT)
	-rm -f src/aux.$(OBJEXT)
	-rm -f src/date.$(OBJEXT)
	-rm -f src/logger.$(OBJEXT)
	-rm -f src/multimedia/csvtools.$(OBJEXT)
	-rm -f src/multimedia/imagemap.$(OBJEXT)
	-rm -f src/multimedia/jpegtools.$(OBJEXT)
	-rm -f src/net/msocket.$(OBJEXT)
	-rm -f src/timemark.$(OBJEXT)
	-rm -f src/timepoint.$(OBJEXT)
	-rm -f src/timeserie.$(OBJEXT)
	-rm -f src/tree/atree.$(OBJEXT)
	-rm -f src/tree/tnode.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/aux.Po
include src/$(DEPDIR)/date.Po
include src/$(DEPDIR)/logger.Po
include src/$(DEPDIR)/timemark.Po
include src/$(DEPDIR)/timepoint.Po
include src/$(DEPDIR)/timeserie.Po
include src/afilter/$(DEPDIR)/adapfil.Po
include src/afilter/$(DEPDIR)/filter.Po
include src/algebra/$(DEPDIR)/matrix3.Po
include src/algebra/$(DEPDIR)/matrix4.Po
include src/algebra/$(DEPDIR)/matrixn.Po
include src/algebra/$(DEPDIR)/quaternion.Po
include src/algebra/$(DEPDIR)/transmatrix.Po
include src/algebra/$(DEPDIR)/vector3.Po
include src/algebra/$(DEPDIR)/vector4.Po
include src/algebra/$(DEPDIR)/vectorn.Po
include src/multimedia/$(DEPDIR)/csvtools.Po
include src/multimedia/$(DEPDIR)/imagemap.Po
include src/multimedia/$(DEPDIR)/jpegtools.Po
include src/net/$(DEPDIR)/msocket.Po
include src/tree/$(DEPDIR)/atree.Po
include src/tree/$(DEPDIR)/tnode.Po

.cpp.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`
install-libtools_aHEADERS: $(libtools_a_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(libtools_a_HEADERS)'; test -n "$(libtools_adir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libtools_adir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libtools_adir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(libtools_adir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(libtools_adir)" || exit $$?; \
	done

uninstall-libtools_aHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(libtools_a_HEADERS)'; test -n "$(libtools_adir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(libtools_adir)'; $(am__uninstall_files_from_dir)

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LIBRARIES) $(HEADERS)
installdirs:
	for dir in "$(DESTDIR)$(libtools_adir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)
	-rm -f src/afilter/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/afilter/$(am__dirstamp)
	-rm -f src/algebra/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/algebra/$(am__dirstamp)
	-rm -f src/multimedia/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/multimedia/$(am__dirstamp)
	-rm -f src/net/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/net/$(am__dirstamp)
	-rm -f src/tree/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/tree/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-noinstLIBRARIES mostlyclean-am

distclean: distclean-am
	-rm -rf src/$(DEPDIR) src/afilter/$(DEPDIR) src/algebra/$(DEPDIR) src/multimedia/$(DEPDIR) src/net/$(DEPDIR) src/tree/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-libtools_aHEADERS

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am:

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf src/$(DEPDIR) src/afilter/$(DEPDIR) src/algebra/$(DEPDIR) src/multimedia/$(DEPDIR) src/net/$(DEPDIR) src/tree/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-libtools_aHEADERS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am check check-am clean clean-generic \
	clean-noinstLIBRARIES ctags distclean distclean-compile \
	distclean-generic distclean-tags distdir dvi dvi-am html \
	html-am info info-am install install-am install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-libtools_aHEADERS install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-libtools_aHEADERS


###############################################################################

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
